[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = direct

lib_deps =
  adafruit/Adafruit PWM Servo Driver Library

platform_packages =
  framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

build_unflags =
  -std=gnu++11
  -std=c++11
  -std=gnu++14
  -std=c++14

build_flags =
  -std=gnu++17